apm install atom-css-comb
apm install atom-live-server
apm install atom-material-ui
apm install auto-update-packages
apm install autocomplete-clang
apm install autocomplete-ctags
apm install autocomplete-java
apm install autocomplete-latex-cite
apm install autocomplete-latex-references
apm install autocomplete-paths
apm install autocomplete-python
apm install build
apm install build-xcodebuild
apm install busy-signal
apm install color-picker
apm install css-declaration-sorter
apm install emmet
apm install file-icons
apm install gpp-compiler
apm install highlight-selected
apm install html-to-css
apm install intentions
apm install jackhammer-syntax
apm install language-arduino
apm install language-ini
apm install language-latex
apm install latex
apm install latex-autocomplete
apm install latex-completions
apm install latex-wordcount
apm install linter-clang
apm install linter-gcc
apm install minimap
apm install minimap-highlight-selected
apm install monokai
apm install open-recent
apm install pane-layout-plus
apm install pastel-dark-syntax
apm install pdf-view
apm install pear-dark-syntax
apm install php-cs-fixer
apm install php-server
apm install pigments
apm install project-manager
apm install remote-comppile
apm install remote-ftp
apm install switch-header-source
apm install teletype
apm install tool-bar
apm install touchbar
apm install tree-view-git-status
