apm install atom-beautify
apm install atom-css-comb
apm install atom-discord
apm install atom-live-server
apm install atom-material-ui
apm install atom-wallaby
apm install auto-update-packages
apm install autocomplete-clang
apm install autocomplete-ctags
apm install autocomplete-java
apm install autocomplete-latex-cite
apm install autocomplete-latex-references
apm install autocomplete-paths
apm install browser-plus
apm install build
apm install build-coffee
apm install build-xcodebuild
apm install busy-signal
apm install city-lights-syntax
apm install color-picker
apm install css-declaration-sorter
apm install dracula-syntax
apm install editorconfig
apm install emmet
apm install file-icons
apm install gpp-compiler
apm install highlight-selected
apm install html-to-css
apm install intentions
apm install isotope-ui
apm install jackhammer-syntax
apm install kimi-syntax
apm install language-arduino
apm install language-ini
apm install language-latex
apm install latex
apm install latex-autocomplete
apm install latex-completions
apm install latex-wordcount
apm install linter
apm install linter-clang
apm install linter-gcc
apm install linter-ui-default
apm install mermaid-dark-syntax
apm install minimap
apm install minimap-highlight-selected
apm install monokai
apm install moonlight
apm install native-ui
apm install nucleus-dark-ui
apm install open-recent
apm install pane-layout-plus
apm install pastel-dark-syntax
apm install pdf-view
apm install pear-dark-syntax
apm install php-cs-fixer
apm install php-server
apm install pigments
apm install platformio-ide
apm install platformio-ide-debugger
apm install platformio-ide-terminal
apm install project-manager
apm install remote-compile
apm install remote-ftp
apm install senusret-syntax
apm install sermon
apm install slate-syntax
apm install soft-era-syntax
apm install styri-syntax
apm install switch-header-source
apm install teletype
apm install test
apm install tool-bar
apm install touchbar
apm install tree-view-git-status
