#!/bin/bash
host="www.google.com"

ping -c1 "$host" &> /dev/null

if [ $? -eq 0 ]; then
  echo "<i class='fas fa-wifi'></i>"
else
  echo "<i class='fas fa-wifi' style='color: rgb(115, 115, 115) !important;''></i>"
fi
